files:
  - source: /modules/admin/locale/admin.pot
    translation: /modules/admin/locale/%two_letters_code%.po
  - source: /modules/album/locale/album.pot
    translation: /modules/album/locale/%two_letters_code%.po
