name: tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '7.2.x'
          - '7.3.x'
          - '7.4.x'

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --no-interaction --ignore-platform-reqs

      - name: Check coding style
        run: composer cs-check
